### ISSUE TITLE
version 0.7.0 kanaBank

### ISSUE THREAD

**Issue by 33Spot** [Atkana/tes3mp-scripts#15]
Hi Kana beautifull work i must say i love yous scripts. I wanted to use kanaBank thought and it works good besides when player puts in the storagebank magic item which has enchantmentCharge for example "enchantmentCharge":123.34074401855 then after closing ans opening again server when i join i cant retrieve my item. I can retrieve all others buts this ons is all locked. It just only has to do with this value as when i manually changed it then i could retrieve my item no porblem. Can you please fix the script so it wont be a problem ?

**Comment by Atkana** [comment]
Unfortunately, I can't seem to replicate this issue using the latest tes3mp release (0.7-alpha w/ commits up to 24th April). If there is a problem, it's likely that it's related to something in tes3mp, rather than the code of the script, so there isn't much I could do about it.

I seem to half-remember there being an issue with not being able to remove particular items from an inventory, but that may have been fixed in a tes3mp hotfix. If you don't have the latest version then you should try using that and see if the issue still persists and get back to me.

On a semi-related note, when investigating the issue, I happened to uncover a bug in tes3mp where a custom item's data is deleted when removed from a container. This applies to any container, not just the ones provided by kanaBank. A patch is being made for tes3mp, so until then it's unadvised to store any custom items inside any containers.

**Comment by 33Spot** [comment]
Thank You Kana! I id not have latest version of tes3mp and now it is working.
Ok I am closing issue thanks!
