### ISSUE TITLE
NPC glitch

### ISSUE THREAD

**Issue by dsk80004** [Atkana/tes3mp-scripts#28]
I've noticed that when you lead a custom npc out of the cell and it resets that the cell still keeps the npc out of the cell but looses all other custom objects.

**Comment by Atkana** [comment]
I'm having trouble understanding your issue. `CellReset` will reset the contents of any cell that isn't marked to be excluded, as well as preserving any objects that have been set to be preserved in a cell that is reset. An NPC who originally belongs to a different cell is always marked to have _their_ object and data preserved (including that they left the cell, if the cell is their starting cell) because otherwise things will break, they don't also cause every _other_ object in the cell to also be protected even if they shouldn't be. If you want other objects to be preserved after a reset, you have to include them in the `scriptConfig.preserveUniqueIndexes` list.

**Comment by dsk80004** [comment]
I'm using cellinserter for testing. What I'm trying to do is make a market
with custom NPCs, although the issue is when one of the merchants leave the
cell and the cell is reset, then the merchant from the cell is still left
in the other cell.

Maybe there is an issue with cellinserter? How would I go about checking if
cellreset has reset the cell?

**Comment by dsk80004** [comment]
If it's not to much to ask could you add me on discord?
Red #9475
